### ISSUE TITLE
Question and proposal

### ISSUE THREAD

**Issue by skarndev** [amoffat/blender-idproperty#3]
Hi, I have a question and a suggestion.
1. Is there anyway I can supply this addon with my addon and get it enabled as just one addon? I tried making it a module but it gave me weird errors.

2. It would be good if validator would not only just check if the item is valid, but would also change the list itself by filtering it.

**Comment by skarnproject** [comment]
Here is also my code: http://pasteall.org/281456/python

**Comment by amoffat** [comment]
> weird errors

You'll have to be more specific

**Comment by skarndev** [comment]
I have a rather big addon that is using your awesome idproperty all over the ui. However, a user needs to install that as a separate addon, else my script will not work. Is there any way to somehow automatically load idproperty as a module? Speaking of the errors, that was when I placed inside modules folder and is probably caused because __init__ is done as an addon.

By validator suggestion, I meant somehow filtering prop_search list from objects where validator returns false. However, I think that is impossible after looking at the code, sadly.

Also I coded a better ray casting based object picker for this. (Similar to unavailable IDProperty used for example to set object parent-child relations). So, you choose a picker, and tap on the object on the scene - done. This way a property can be used inside the object panel or mesh panel as it does not depend on object selection anymore. Should I make a pull request or something?

**Comment by amoffat** [comment]
Yeah, I believe if you include this in your own addon, the main problem will be initialization ordering.  You'll need to import idproperty first, then in your `register()` you'll need to initialize `idproperty.register()` before you do any of your own initialization.  Similarly with `unregister()`...you'll need to do `idproperty.unregister()` *last* after all of your unregistering.

Re: object picker.  Sure, open a pull request.  Sounds like a nice addition.

**Comment by skarndev** [comment]
Thanks for help, that should probably work. Also, I made a pull request.
